import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  hero: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 380,
  },
  heroImage: {
    width: '100%',
    height: '100%',
    opacity: 0.92,
  },
  heroOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
  },
  safeArea: {
    flex: 1,
  },
  topFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 140,
  },
  topBar: {
    paddingHorizontal: 16,
    paddingTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
  },
  topTitle: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  topBarSpacer: {
    width: 44,
    height: 44,
  },
  scrollContent: {
    paddingTop: 232,
    paddingHorizontal: 20,
    paddingBottom: 140,
  },
  headerBlock: {
    paddingTop: 10,
  },
  classTitle: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  classMeta: {
    marginTop: 12,
    color: '#E4E4E7',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 2,
  },
  classMetaStrong: {
    color: '#FFFFFF',
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  classMetaMuted: {
    color: '#D4D4D8',
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  statusBadge: {
    alignSelf: 'flex-start',
    marginTop: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  missingMeta: {
    marginTop: 10,
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  loadingBlock: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 10,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    color: '#71717A',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  errorTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  instructorCard: {
    marginTop: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1F1F23',
    backgroundColor: '#101012',
  },
  instructorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  instructorText: {
    flex: 1,
  },
  sectionKicker: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  instructorName: {
    marginTop: 6,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 1,
  },
  descriptionBlock: {
    marginTop: 22,
  },
  descriptionText: {
    marginTop: 14,
    color: '#B6B6BE',
    fontSize: 16,
    lineHeight: 27,
  },
  detailsBlock: {
    marginTop: 22,
  },
  detailsCard: {
    marginTop: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#1F1F23',
    backgroundColor: '#101012',
    overflow: 'hidden',
  },
  detailsDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#1F1F23',
  },
  detailRow: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailLabel: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  detailValue: {
    flex: 1,
    textAlign: 'right',
    color: '#E4E4E7',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  tagsWrap: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tagChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#1F1F23',
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  tagChipText: {
    color: '#A1A1AA',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  bottomCtaWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  bottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    top: -34,
  },
  ctaButton: {
    height: 56,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOpacity: 0.35,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 10 },
      },
      android: {
        elevation: 8,
      },
    }),
  },
  ctaButtonDisabled: {
    opacity: 0.92,
  },
  ctaText: {
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
});
